version = 0.1

[default.deploy.parameters]
stack_name = "sam-blog-server"
resolve_s3 = true
s3_prefix = "sam-blog-server"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DBUsername=\"blogadmin\" DBName=\"database123456\""
image_repositories = []
